---
title: "Practicando"
author: "Fernando"
date: "20/2/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(knitr)
library(gapminder)
knitr::opts_chunk$set(echo = TRUE)
```


## Primeros pasos

En este documentos se plasman los primeros pasos del uso de Git en RStudio. Para este primer ejercicio se hace uso de la base de datos **gapminder**.

```{r}
colnames(gapminder)
```


```{r}
gapminder %>%
  filter(continent == 'Americas', year == 2007) %>%
  ggplot(aes(x=lifeExp, y=country )) + 
  geom_point()
```

```{r}
gapminder %>%
  mutate(pop_m = round(pop / 1000000, 2))
```


Ordenar datos

```{r}
gapminder %>%
  filter(year == 2007 & continent == "Americas") %>%
  arrange(gdpPercap) %>%
  ggplot(aes(x=gdpPercap, y=country)) + 
  geom_point()
```

```{r}
gapminder %>%
  summarise(max_edv = max(lifeExp ))

gapminder %>%
  filter(lifeExp >= 82.6)
```

 
```{r}
gapminder %>%
  group_by(year) %>%
  summarise(mean_edv = mean(lifeExp) )
```

```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarise(sum_pop = sum(as.numeric(pop)),
            mean_pop = mean(pop),
            mean_edv = mean(lifeExp),
            n_paises =n()) %>%
  ggplot(aes(x = year,
             y = mean_edv,
             color = continent)) +
  geom_line()
```


## Uso de ggplot2

```{r}
year <- c('2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018')
disney <- c(11, 13, 11, 8, 12, 11, 12, 8, 10)

plot(x = year,
     y = disney)
```

```{r}
peliculas <- data.frame(year,disney)

kable(peliculas)

ggplot(data = peliculas,
       mapping = aes(x = year, y = disney)) +
  geom_point()
```



```{r}

gapminderpt <- gapminder %>%
  filter(country == 'Portugal') 
  
plot(x = gapminderpt$year,
     y = gapminderpt$lifeExp)

ggplot(data = gapminderpt,
       mapping = aes(x = year, y = lifeExp )) +
  geom_line()

```



```{r}

gapminderpt <- gapminder %>%
  filter(country == 'Portugal') 
  
ggplot(data = gapminderpt,
       mapping = aes(x = year, y = lifeExp )) +
  geom_point() +
  geom_smooth(method = 'lm')

```



## Graficos de barras


```{r}
gapminder2007 <- gapminder %>%
  filter(year == 2007)

kable(gapminder2007)


barplot(table(gapminder2007$continent))

ggplot(data = gapminder2007,
       mapping = aes(x = continent )) +
       geom_bar() 
```



```{r}
gapminder2007 <- gapminder2007 %>%
  mutate(lifeExp_label = case_when(
    
    lifeExp < 50 ~ 'baja',
    lifeExp < 70 ~ 'media',
    TRUE ~ 'alta'
    
  ))

p <- ggplot(data = gapminder2007,
            mapping = aes(x = continent, 
                          fill = lifeExp_label))

p + geom_bar(position = 'stack', stat = 'count')
```
































